// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AplicativoDeAlmacen.Models.Models;
using AplicativoDeAlmacen.Models.Users;
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models;

public partial class PersonaComercial
{
    public int Id { get; set; }

    // El tipo de persona clásico (Natural o Jurídica)
    public TipoPersona TipoPersona { get; set; }

    // 🌟 NUEVO: La categorización comercial (Persona, Colegio, Empresa)
    public TipoPersonaComercial TipoPersonaComercial { get; set; }

    public string Nombres { get; set; }

    public string ApellidoPaterno { get; set; }

    public string ApellidoMaterno { get; set; }

    public string RazonSocial { get; set; }

    public string NombreComercial { get; set; }

    public string Ruc { get; set; }

    public string Dni { get; set; }

    public Localidad Localidad { get; set; }

    public Departamento Departamento { get; set; }

    public Provincia Provincia { get; set; }

    public Distrito Distrito { get; set; }

    public string Direccion { get; set; }

    public ZonaPromotoria ZonaPromotoria { get; set; }

    public Estado Estado { get; set; }

    // 🌟 NUEVO: Para saber qué usuario del sistema registró a este cliente
    public int? UsuarioId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    // 🌟 NUEVO (Opcional pero recomendado): Relación hacia sus precios especiales
    public List<ClientePrecioEspecial> PreciosEspeciales { get; set; } = new List<ClientePrecioEspecial>();
}