// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models
{
    public partial class Usuario
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Nombres { get; set; }
        public string Password { get; set; }
        public bool Estado { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        // Clave Foránea
        public int RolUsuarioId { get; set; }

        // PROPIEDAD DE NAVEGACIÓN: Relación de objeto fuertemente tipado
        public RolesUsuario Rol { get; set; } = new RolesUsuario();

        // Propiedad calculada para visualización amigable en la UI
        public string EstadoNombre => Estado ? "ACTIVO" : "INACTIVO";
    }
}