// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models;

public partial class Coleccion
{
    public int Id { get; set; }

    public int EstadoId { get; set; }

    public int? Ano { get; set; }
}