// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models;

public partial class Movimiento
{
    public int Id { get; set; }

    public DateOnly? FechaMovimiento { get; set; }

    public string SerieDocumento { get; set; }

    public string NumeroDocumento { get; set; }

    public MotivoProducto MotivoProducto { get; set; }

    public Ubicacion Ubicacion { get; set; }

    public Usuario Usuario { get; set; }

    public PersonaComercial PersonaComercial { get; set; }

    public string SerieGuia { get; set; }

    public string NumeroGuia { get; set; }

    public string Observacion { get; set; }

    public Estado Estado { get; set; }

    public DateTime? CreatedAt { get; set; }
}