// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models;

public partial class PersonaComercial
{
    public int Id { get; set; }

    public string TipoPersona { get; set; }

    public string Nombres { get; set; }

    public string ApellidoPaterno { get; set; }

    public string ApellidoMaterno { get; set; }

    public string RazonSocial { get; set; }

    public string NombreComercial { get; set; }

    public string Ruc { get; set; }

    public string Dni { get; set; }

    public Localidad Localidad { get; set; }

    public Departamento Departamento { get; set; }

    public Provincia Provincia { get; set; }

    public Distrito Distrito { get; set; }

    public string Direccion { get; set; }

    public ZonaPromotoria ZonaPromotoria { get; set; }

    public Estado Estado { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}