// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models;

public partial class PersonaComercial
{
    public int Id { get; set; }

    public int TipoPersonaId { get; set; }

    public string Nombres { get; set; }

    public string ApellidoPaterno { get; set; }

    public string ApellidoMaterno { get; set; }

    public string RazonSocial { get; set; }

    public string NombreComercial { get; set; }

    public string Ruc { get; set; }

    public string Dni { get; set; }

    public int? LocalidadId { get; set; }

    public int? DepartamentoId { get; set; }

    public int? ProvinciaId { get; set; }

    public int? DistritoId { get; set; }

    public string Direccion { get; set; }

    public int? ZonaPromotoriaId { get; set; }

    public int EstadoId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}