// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models;

public partial class Producto
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public string Abreviatura { get; set; }

    public int? Cantidad { get; set; }

    public int? UnidadMedidaId { get; set; }

    public int? TipoProductoId { get; set; }

    public decimal? PrecioUnitario { get; set; }

    public decimal? Porcentaje { get; set; }

    public int? NivelId { get; set; }

    public int? GradoId { get; set; }

    public int? CursoId { get; set; }

    public int? TituloCursoId { get; set; }

    public int? AfectacionIgvId { get; set; }

    public int? EstadoId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
    public UnidadMedida UnidadMedida { get; set; } 

    public  AfectacionIgv afectacion { get; set; } 
    public Estado Estado { get; set; }

}