// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models;

public partial class RegistroCodigo
{
    public int Id { get; set; }

    public int ColeccionId { get; set; }

    public int Cantidad { get; set; }

    public string Desde { get; set; }

    public string Hasta { get; set; }

    public int? CategoriaProductoId { get; set; }

    public int? ProductoId { get; set; }
}