// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models;

public partial class Ubicacion
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public int TipoUbicacionId { get; set; }

    public int LocalidadId { get; set; }

    public string Direccion { get; set; }

    public int EstadoId { get; set; }

    public int? DepartamentoId { get; set; }

    public int? ProvinciaId { get; set; }

    public int? DistritoId { get; set; }
}