// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models;

public partial class MovimientoDetalle
{
    public int Id { get; set; }

    public int MovimientoId { get; set; }

    public int ProductoId { get; set; }

    public decimal CantidadIngreso { get; set; }

    public decimal CantidadSalida { get; set; }

    public decimal? CostoUnitario { get; set; }

    public DateTime CreatedAt { get; set; }
}