// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models;

public partial class MovimientoCodigo
{
    public int Id { get; set; }

    public int MovimientoId { get; set; }

    public int MovimientoDetalleId { get; set; }

    public int CodigoCreadoId { get; set; }

    public int? CantidadIngreso { get; set; }

    public int? CantidadSalida { get; set; }

    public DateTime CreatedAt { get; set; }
}