// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models;

public partial class Movimiento
{
    public int Id { get; set; }

    // 🌟 DateTime para conservar fecha y hora operativa exacta
    public DateTime? FechaMovimiento { get; set; }

    public string SerieDocumento { get; set; }

    public string NumeroDocumento { get; set; }

    public int MotivoProductoId { get; set; }

    public int? UbicacionId { get; set; }
    public int? AlmacenId { get; set; }

    public int? AlmacenOrigenId { get; set; }
    public int? AlmacenDestinoId { get; set; }

    public int UsuarioId { get; set; }
    public int? UsuarioUpdateId { get; set; } // 🌟 NUEVO: Usuario que editó

    public int? PersonaComercialId { get; set; }

    public string SerieGuia { get; set; }

    public string NumeroGuia { get; set; }

    public string Observacion { get; set; }

    public int EstadoId { get; set; }
    public string TipoMovimiento { get; set; }

    public DateTime? CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; } // 🌟 NUEVO: Fecha/hora de última edición
}