<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon-almacen.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ViewModels\ViewModels\**" />
    <EmbeddedResource Remove="ViewModels\ViewModels\**" />
    <None Remove="ViewModels\ViewModels\**" />
    <Page Remove="ViewModels\ViewModels\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="fondo-opcional.jpg" />
    <None Remove="Videos\fondo-video.mp4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon-almacen.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="FontAwesomeInstaller\" />
    <Folder Include="Helpers\" />
    <Folder Include="Icon\" />
    <Folder Include="Images\" />
    <Folder Include="Videos\" />
    <Folder Include="ViewModels\" />
    <Folder Include="Views\Elementos Visuales\" />
  </ItemGroup>

  <!-- Excluir archivo de XAML duplicado que causa conflictos tras movimiento de ventana -->
  <ItemGroup>
    <Page Remove="Views\Movimientos\Entrada\ImportarCodigos.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.1.2" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.5" />
    <PackageReference Include="MaterialDesignThemes" Version="5.1.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="Notification.Wpf" Version="10.1.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="fondo-opcional.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Audio\UI\bienvenida.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
