// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AplicativoDeAlmacen.Models.Models;

public partial class Ubicacion
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public TipoUbicacion TipoUbicacion { get; set; }

    public Localidad Localidad { get; set; }

    public string Direccion { get; set; }

    public Estado Estado { get; set; }

    public Departamento Departamento { get; set; }

    public Provincia Provincia { get; set; }

    public Distrito Distrito { get; set; }
}